version: "3"

services:
  rails:
    build: .
    container_name: profile
    image: calvincaulfield/profile
    ports:
      - 3002:3002
    network_mode: "host"
    restart: always
    env_file:
      - env/.env-stage
