version: "3"

services:
  rails:
    build: .
    container_name: profile
    image: calvincaulfield/profile
    ports:
      - 3002:3002
    restart: always
    environment:
      - DB_DATABASE=something
    env_file:
      - env/.env-stage
