version: '3'

services:
  rails:
    build: .
    image: calvincaulfield/profile
    ports:
      - 3002:3002
    network_mode: "host"
    restart: always
    environment:
      - DB_DATABASE=something
    env_file:
      - ../.env

