version: '3'

services:
  rails:
    build: .
    image: calvincaulfield/profile
    ports:
      - ${PROFILE_PORT}:${PROFILE_PORT}
    network_mode: "host"
    restart: always
    environment:
      - DB_DATABASE=something
    env_file:
      - ../.env-docker
    command: rails s --binding 0.0.0.0 -p ${PROFILE_PORT}

